### ISSUE TITLE
Rename artifact so it doesn't clash with `io.gatling:gatling-jdbc`

### ISSUE THREAD

**Issue by slandelle** [codecentric/gatling-jdbc#8]
Hi there,

I know this request is a PITA, all the more as this project is actively developed and is seems to be gaining more traction.
Sadly, the artifact id you picked clashes with `io.gatling:gatling-jdbc` (that contains the code for `jdbcFeeder`).
It brings confusion and one can't have both when using Gatling's bundle distrib.

Maybe at some point we'll forbid third parties to use the `gatling-` prefix to avoid such confusion and clashes, just like maven does.

Could you please consider renaming it?

Kind regards

**Comment by rbraeunlich** [comment]
Hi @slandelle 

I can understand the problem here. Basically, I'd like to keep the two parts "gatling" and "jdbc" somehow in the artifact name. Is there any recommendation from you, which naming scheme third-party libraries should follow?

Cheers,
Ronny

**Comment by slandelle** [comment]
> Is there any recommendation from you, which naming scheme third-party libraries should follow?

Third party maven plugins tend to switch order, eg `maven-scala-plugin` became `scala-maven-plugin`.

So here, it would be `jdbc-gatling`.

Or have prefix, eg `codecentric-gatling-jdbc`.

Thanks for your understanding.

**Comment by rbraeunlich** [comment]
Done with 1135364e695edfb41d5de40c6fe20c2a5ff4717c

**Comment by slandelle** [comment]
Thanks a lot!
